#!/bin/bash
#write sources
DIST="bookworm"
rm nearline.list
for DIRECTORY in $(ls *.d -d );
  do
	  MAIN=""
	  CONTRIB=""
	  NONFREE=""

if [ -d "${DIRECTORY}/dists/${DIST}/main" ]; then
	  MAIN="main"
fi

if [ -d "${DIRECTORY}/dists/${DIST}/contrib" ]; then
	  CONTRIB="contrib"
fi

if [ -d "${DIRECTORY}/dists/${DIST}/non-free" ]; then
	  NONFREE="non-free"
fi

echo deb [trusted=yes] http://deb12.home/${DIRECTORY} ${DIST} $MAIN $CONTRIB $NONFREE
echo deb [trusted=yes] http://deb12.home/${DIRECTORY} ${DIST} $MAIN $CONTRIB $NONFREE >> nearline.list
done
echo deb [trusted=yes] http://deb12.home/local ./ >> nearline.list

cp nearline.list /var/www/html/list/etc/apt/sources.list.d/
dpkg-deb --root-owner-group --build list
cp list.deb local/

