#!/bin/bash
wget -c -r -np -l 1 -A jigdo,template https://cdimage.debian.org/debian-cd/current/amd64/jigdo-dvd/

find cdimage.debian.org -type f -exec cp {} ./ \;
cd got
find  -type f -exec rm ../{} \;
cd ..
#don't need to sort base images and updates now that we have rdfind
#rm debian-12*
#rm debian-update*
#jigsaw download the iso's auto scan existing and jigdo
find -maxdepth 1 -type f -name '*.jigdo' -exec jigdo-lite {} --scan /var/www/html --noask \;
find -maxdepth 1 -type f -name '*.iso' -exec ./unpack-iso {} \;
#generate new source file
./gen-src
./refresh-local

#cleanup
find -maxdepth 1 -type f -name '*.jigdo' -exec mv {} got/ \;
find -maxdepth 1 -type f -name '*.template' -exec mv {} got/ \;

rdfind -dryrun true -makehardlinks true debian*
